import { SupportedLocale } from './types';

export const TARGET_LANGUAGES = [
  { code: 'en-US', label: 'English (US)' },
  { code: 'en-GB', label: 'English (UK)' },
  { code: 'zh-CN', label: 'Chinese (Simplified)' },
  { code: 'zh-TW', label: 'Chinese (Traditional)' },
  { code: 'ja', label: 'Japanese' },
  { code: 'ko', label: 'Korean' },
  { code: 'fr', label: 'French' },
  { code: 'de', label: 'German' },
  { code: 'es', label: 'Spanish' },
];

export const UI_STRINGS: Record<SupportedLocale, Record<string, string>> = {
  [SupportedLocale.EN]: {
    appTitle: 'PolyGlot Bridge',
    uploadTitle: 'Upload Documents',
    uploadDesc: 'Drag & drop files here, or click to select',
    supportedFormats: 'Supports .txt, .md, .docx, .pptx, .xlsx, .srt, .pdf (Programmatic)',
    source: 'Source',
    target: 'Target',
    status: 'Status',
    batchProgress: 'Batch Progress',
    download: 'Download',
    translating: 'Translating...',
    completed: 'Completed',
    queued: 'Queued',
    autoDetect: 'Auto Detect',
    selectTarget: 'Select Target Language',
    dropFiles: 'Drop files to upload',
  },
  [SupportedLocale.ZH_CN]: {
    appTitle: '多语桥接',
    uploadTitle: '上传文档',
    uploadDesc: '拖放文件至此，或点击选择',
    supportedFormats: '支持 .txt, .md, .docx, .pptx, .xlsx, .srt, .pdf (编程版)',
    source: '源文件',
    target: '目标文件',
    status: '状态',
    batchProgress: '批量进度',
    download: '下载',
    translating: '翻译中...',
    completed: '已完成',
    queued: '排队中',
    autoDetect: '自动检测',
    selectTarget: '选择目标语言',
    dropFiles: '释放文件以上传',
  },
  [SupportedLocale.ZH_TW]: {
    appTitle: '多語橋接',
    uploadTitle: '上傳文檔',
    uploadDesc: '拖放文件至此，或點擊選擇',
    supportedFormats: '支持 .txt, .md, .docx, .pptx, .xlsx, .srt, .pdf (編程版)',
    source: '源文件',
    target: '目標文件',
    status: '狀態',
    batchProgress: '批量進度',
    download: '下載',
    translating: '翻譯中...',
    completed: '已完成',
    queued: '排隊中',
    autoDetect: '自動檢測',
    selectTarget: '選擇目標語言',
    dropFiles: '釋放文件以上傳',
  },
  [SupportedLocale.JA]: {
    appTitle: 'PolyGlot Bridge',
    uploadTitle: 'ドキュメントをアップロード',
    uploadDesc: 'ファイルをここにドラッグ＆ドロップ、またはクリックして選択',
    supportedFormats: '.txt, .md, .docx, .pptx, .xlsx, .srt, .pdf (テキスト版) に対応',
    source: 'ソース',
    target: 'ターゲット',
    status: 'ステータス',
    batchProgress: 'バッチ進行状況',
    download: 'ダウンロード',
    translating: '翻訳中...',
    completed: '完了',
    queued: '待機中',
    autoDetect: '自動検出',
    selectTarget: 'ターゲット言語を選択',
    dropFiles: 'ファイルをドロップしてアップロード',
  },
  [SupportedLocale.KO]: {
    appTitle: 'PolyGlot Bridge',
    uploadTitle: '문서 업로드',
    uploadDesc: '파일을 여기에 드래그 앤 드롭하거나 클릭하여 선택하세요',
    supportedFormats: '.txt, .md, .docx, .pptx, .xlsx, .srt, .pdf (프로그래밍 방식) 지원',
    source: '원본',
    target: '대상',
    status: '상태',
    batchProgress: '일괄 처리 진행률',
    download: '다운로드',
    translating: '번역 중...',
    completed: '완료됨',
    queued: '대기 중',
    autoDetect: '자동 감지',
    selectTarget: '대상 언어 선택',
    dropFiles: '파일을 드롭하여 업로드',
  },
};